### ISSUE TITLE
Blank Page -- Internal Server Error 500

### ISSUE THREAD

**Issue by lslamp** [daveismyname/simple-blog-part-1-build#10]
Greetings, thanks for this code, but I am very new to php and have no clue what I did wrong.

Basically I downloaded the zip file. renamed the top level dir to blog
I ran the db.sql on my database. I can connect to the db and run queries on the tables created in the script. So I am sure that the db part is working.

I editied the includes/config.php and made the following changes.

//database credentials
define('DBHOST','localhost');
define('DBUSER','blogadmin');
define('DBPASS','xxxxxxxxx');
define('DBNAME','blogphp');
define('DBPORT','3306');

$db = new PDO("mysql:host=".DBHOST.";DBPORT;dbname=".DBNAME, DBUSER, DBPASS);

I then tried to load the page and am getting the Internal Server Error 500.

![image](https://user-images.githubusercontent.com/6013759/105259608-6b60ff00-5b8c-11eb-9392-2d34d2b95095.png)

Any ideas what I have done wrong.
Thanks
Lawrence

**Comment by dcblogdev** [comment]
500 means there’s a server error that can be a number of things, you should have an error_log file somewhere on your server that would tell you more details about the error,

It would be there’s an issue with the version of php being used for instance its very hard to pinpoint without seeing what the error is.

**Comment by dcblogdev** [comment]
500 means there’s a server error that can be a number of things, you should have an error_log file somewhere on your server that would tell you more details about the error,

It would be there’s an issue with the version of php being used for instance its very hard to pinpoint without seeing what the error is.
