### ISSUE TITLE
Malawijournalnews

### ISSUE THREAD

**Issue by Malawijournalnews** [daveismyname/simple-blog-part-1-build#4]
![tn_malawijournalnews](https://user-images.githubusercontent.com/35185592/35960505-fb29a7ee-0cfd-11e8-8558-4a774d872a58.png)
[~txt04re.txt](https://github.com/daveismyname/simple-blog-part-1-build/files/1706061/txt04re.txt)
[Uploading ~txtvbqi.txt…]()
![Uploading WC6_Gabarit_Image_200x150_C.png…]()

**Comment by dcblogdev** [comment]
???
