### ISSUE TITLE
Link to tutorial results in 404 page

### ISSUE THREAD

**Issue by mladoux** [daveismyname/simple-blog-part-1-build#5]
You are using the link 'http://daveismyname.blog/creating-a-blog-from-scratch-with-php-bp' in your readme.md, which results in a 404 error page, I can get to the front page of your tutorial with 'https://daveismyname.blog/creating-a-blog-from-scratch-with-php'

**Comment by dcblogdev** [comment]
Thanks I’ve updated the link.
