### ISSUE TITLE
Content is limited to display 

### ISSUE THREAD

**Issue by ghost** [daveismyname/simple-blog-part-1-build#7]
Hi.

When I write a post , I write the title, the description , and content

the content is limited to about 27 line only , while in phpmyadmin , I find all the content correct.

where is the problem ?

thx for helping me

**Comment by ghost** [comment]
It was my fault , a css problem when setting the content div height to 100vh.

**Comment by Daniel7D3v** [comment]
How did I even get subscribed to this?

**Comment by dcblogdev** [comment]
@Daniel7D3v you're watching the repo which will notify you about all activities, to Avoid this you can click the unwatch button on the top right.
